export 'landing_screen/landing_screen_bloc.dart';
export 'university/university_bloc.dart';
export 'campus/campus_bloc.dart';
export 'major/major_bloc.dart';
export 'authentication/authentication_bloc.dart';
export 'role/role_app_bloc.dart';
export 'campaign/campaign_bloc.dart';
export 'brand/brand_bloc.dart';
export 'voucher/voucher_bloc.dart';