// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBkoGAwaJMubvQ1xHjUnjfSqfDuwgy4U',
    appId: '1:1069589510922:web:2476c0a087ef9a3a5298f3',
    messagingSenderId: '1069589510922',
    projectId: 'unibean-app',
    authDomain: 'unibean-app.firebaseapp.com',
    storageBucket: 'unibean-app.appspot.com',
    measurementId: 'G-5YR7GVZGJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcgROJQwxJMhhT4MWE8NLoxQkvewUhQo',
    appId: '1:1069589510922:android:49effad45b88b80e5298f3',
    messagingSenderId: '1069589510922',
    projectId: 'unibean-app',
    storageBucket: 'unibean-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFuwZun40p4n6PlODuESanoXRJd5XiX0',
    appId: '1:1069589510922:ios:3fc5aa0e7fb40aac5298f3',
    messagingSenderId: '1069589510922',
    projectId: 'unibean-app',
    storageBucket: 'unibean-app.appspot.com',
    iosBundleId: 'com.example.unibeanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFuwZun40p4n6PlODuESanoXRJd5XiX0',
    appId: '1:1069589510922:ios:0c654335f3a7c0bc5298f3',
    messagingSenderId: '1069589510922',
    projectId: 'unibean-app',
    storageBucket: 'unibean-app.appspot.com',
    iosBundleId: 'com.example.unibeanApp.RunnerTests',
  );
}
