export 'entities/major.dart';
export 'entities/university.dart';
export 'entities/campus.dart';
export 'entities/user.dart';
export 'entities/student.dart';
export 'entities/campaign.dart';
export 'entities/challenge.dart';
export 'entities/voucher.dart';
export 'entities/brand.dart';