name: unibean_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #google_fonts
  google_fonts: ^6.1.0

  #splash
  flutter_native_splash: ^2.3.8

  #image picker
  image_picker: ^1.0.4

  #dateformat
  intl: ^0.19.0

  #use otp 
  otp_text_field: ^1.1.3

  #bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #svg
  flutter_svg: ^2.0.9

  #carousel_slider
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0



# Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: assets/images/background_splash.png
  image: assets/images/logo_splash.png

#   android_12:
#     background_image: assets/images/background_splash.png
#     image: assets/images/logo_splash.png
  
#   web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter laucher icons
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  anroid: "launcher_icon"
  image_path: "assets/icons/logo_bean.png"



flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
